name: Delete Tags and GitHub Releases
description: An action to delete a tag, and optionally its associated release.
author: "Clement Tsang"

branding:
  color: "red"
  icon: "delete"

inputs:
  tag_name:
    description: tag name
    required: true
  delete_release:
    description: whether to delete release or not
    required: false
    default: true
  repo:
    description: target repository as <owner>/<repository>
    required: false
  delete_no_draft:
    description: whether published (non-draft) releases can be deleted
    required: false
    default: false

runs:
  using: "node20"
  main: "index.js"
